language: node_js
sudo: false

node_js:
  - "10"

cache:
  directories:
  - node_modules

jobs:
  include:
    - stage: test
      script:
        - npm i
        - travis_wait 30 npm run bootstrap
        - npm run build
        - npm run test:ci
    - stage: publish
      if: (branch = master) AND (NOT (type IN (pull_request)))
      script: npm run build:docs
      deploy:
        - provider: pages
          skip_cleanup: true
          github-token: $GITHUB_TOKEN
          local-dir: docs/.vuepress/dist
          on:
            branch: master
